# Generated by Django 4.2.5 on 2023-09-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivered',
            options={'verbose_name': 'Delivered', 'verbose_name_plural': 'Delivered'},
        ),
        migrations.AlterModelOptions(
            name='veterinarian',
            options={'verbose_name': 'Veterinarians', 'verbose_name_plural': 'Veterinarians'},
        ),
    ]
