# Generated by Django 4.2.5 on 2023-09-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delivered_created_at_veterinarian_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
