# Generated by Django 4.2.5 on 2023-09-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_veterinarian_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon',
            field=models.CharField(max_length=255),
        ),
    ]
