# Generated by Django 4.2.5 on 2023-11-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='day',
            field=models.DateField(),
        ),
    ]
