# Generated by Django 4.2.5 on 2023-11-05 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_veterinarian_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.IntegerField()),
                ('day', models.DateField()),
                ('product_count', models.IntegerField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
