# Generated by Django 4.2.5 on 2023-11-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_registration_delivered_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placing',
            options={'verbose_name': 'Placing', 'verbose_name_plural': 'Placing'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Registration', 'verbose_name_plural': 'Registration'},
        ),
    ]
