# Generated by Django 4.2.5 on 2023-11-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Bot Foydalanuvchilari', 'verbose_name_plural': 'Bot Foydalanuvchilari'},
        ),
    ]
